am pus tema selenium
SkillBrain-com/Procyon-QAC-G1-13.10.22 pull request #12
Opened 2023-01-07 19:11 UTC by Cosmin0589

2023-01-08 08:36 UTC, 95teo requested changes
Let's try to make a call these days. It looks like you've created an entire new maven project and it's not necessary. We only need the java classes. Thanks!:D

2023-01-11 14:44 UTC, 95teo requested changes
You are missing the other 3 pages from https://testpages.herokuapp.com/styled/index.html and also you have nothing for https://demoqa.com/elements. Please read again the homework requirements. Thanks!

2023-01-11 14:44 UTC, 95teo commented on src/test/java/cosminsechel/tests/seleniumpart1/TablePageTests.java
> +
Leave only one blank line here. Thanks!

2023-01-12 07:25 UTC, 95teo requested changes

2023-01-12 07:25 UTC, 95teo commented on src/main/java/cosminsechel/driver/BrowserManager.java
> +    }
You forgot to add driver.quit() inside this method. Don't leave the method body empty. Thanks!

2023-01-12 07:25 UTC, 95teo commented on src/test/java/cosminsechel/tests/seleniumpart1/Demoqatema.java
> +    public static void main(String[] args) throws InterruptedException {
You are opening multiple browser instances. We only need one.

2023-01-12 07:25 UTC, 95teo commented on src/test/java/cosminsechel/tests/seleniumpart1/Demoqatema.java
> +        BrowserManager.createDriver();
Remove this line. Thanks!

2023-01-12 07:25 UTC, 95teo commented on src/test/java/cosminsechel/tests/seleniumpart1/Demoqatema.java
> +        WebDriver driver = new ChromeDriver();
This line should be using the BrowserManager.createDriver() method -> update existing line to ->
WebDriver driver = BrowserManager.createDriver();

2023-01-12 07:25 UTC, 95teo commented on src/test/java/cosminsechel/tests/seleniumpart1/Demoqatema.java
> +
Please close the browser at the end. You can use the method defined in BrowserManager.

2023-01-12 07:25 UTC, 95teo commented on src/test/java/cosminsechel/tests/seleniumpart1/Test.java
> +        BrowserManager.createDriver();
Same comments as in the previous class. Thanks!

2023-01-12 07:25 UTC, 95teo commented on src/test/java/cosminsechel/tests/seleniumpart1/Test.java
> +
You can remove these two blank lines from here as they are not needed. Thanks!

2023-01-12 15:35 UTC, sorinfoca approved these changes

2023-01-13 05:51 UTC, 95teo requested changes

2023-01-13 05:51 UTC, 95teo commented on src/test/java/cosminsechel/tests/seleniumpart1/Demoqatema.java
> +            closeBrowser();
Move the closeBrowser(); call after if - else block. We want to close always the browser, not only if we're not selecting the checkbox. Thanks!

2023-01-13 05:51 UTC, 95teo commented on src/test/java/cosminsechel/tests/seleniumpart1/Demoqatema.java
> +    private static void closeBrowser() {
You can remove this method from here as you defined the closeBrowser in BrowserManager class. That's the method you want to use to close the browser.

2023-01-13 05:51 UTC, 95teo commented on src/test/java/cosminsechel/tests/seleniumpart1/Test.java
> +        BrowserManager.createDriver();
You forgot to delete this line so please remove it. Thanks!

2023-01-13 05:51 UTC, 95teo commented on src/test/java/cosminsechel/tests/seleniumpart1/Test.java
> +    }
Add BrowserManager.closeChromeDriver(driver) at the end to close the browser. Thanks!

2023-01-14 19:04 UTC, 95teo approved these changes

2023-01-14 19:32 UTC, merged