First commit
SkillBrain-com/Procyon-QAC-G1-13.10.22 pull request #22
Opened 2023-01-11 22:18 UTC by SanduBogdan95

2023-01-13 06:43 UTC, 95teo requested changes

2023-01-13 06:43 UTC, 95teo commented on src/test/java/teofilursan/tests/seleniumpart1/SeleniumExampleTest.java
> -package teofilursan.tests.seleniumpart1;
Please don't remove this class yet. Thanks!

2023-01-13 06:43 UTC, 95teo commented on src/test/java/BogdanSandu/tests/Tema6/HerokuForms.java
> +        WebElement submitButton = driver.findElement(By
Please complete some form details before clicking on submit button. Thanks!

2023-01-13 06:43 UTC, 95teo commented on src/test/java/BogdanSandu/tests/Tema6/HerokuForms.java
> +
You are missing the try - catch block. Please add it.

2023-01-13 06:43 UTC, 95teo commented on src/test/java/BogdanSandu/tests/Tema6/DemoQaWindow.java
> +
You are missing the try - catch block. Please add it.

2023-01-13 06:43 UTC, 95teo commented on src/test/java/BogdanSandu/tests/Tema6/DemoQaWindow.java
> +
Add interactions with other buttons too - there are two more on this page, not only the one showed at retro. Thanks!

2023-01-14 19:19 UTC, 95teo requested changes

2023-01-14 19:19 UTC, 95teo commented on src/test/java/BogdanSandu/tests/Tema6/DemoQaWindow.java
> +            clickOnNewTabButton();
Do you have any exceptions that can be thrown inside this try? That means to identify in one of your methods an element with a wrong id/selector/xpath. ;)

2023-01-14 19:19 UTC, 95teo commented on src/test/java/BogdanSandu/tests/Tema6/HerokuForms.java
> +            fillFormDetails();
Do you have any exceptions that can be thrown inside this try? That means to identify in one of your methods an element with a wrong id/selector/xpath. ;)

2023-01-14 19:19 UTC, 95teo commented on src/test/java/BogdanSandu/tests/Tema6/DemoQaWindow.java
> +    public static void closeBrowser() {
No need to declare here one extra closeBrowser() method. You can use the one from BrowserManager. Thanks!

2023-01-14 19:19 UTC, 95teo commented on src/test/java/BogdanSandu/tests/Tema6/HerokuAlerts.java
> +    public static void closeBrwoser(){
No need to declare here one extra closeBrowser() method. You can use the one from BrowserManager. Thanks!

2023-01-14 19:19 UTC, 95teo commented on src/test/java/BogdanSandu/tests/Tema6/HerokuForms.java
> +    public static void closeBrowser () {
No need to declare here one extra closeBrowser() method. You can use the one from BrowserManager. Thanks!

2023-01-16 07:08 UTC, 95teo requested changes

2023-01-17 06:50 UTC, 95teo requested changes

2023-01-17 06:50 UTC, 95teo commented on src/main/java/bogdanSandu/driver/BrowserManager.java
> +package BogdanSandu.driver;
Packages in Java should start with lower and not capital letters so please leave the package name to bogdanSandu. Also do this change for the package inside test/java. Thanks!

2023-01-17 06:50 UTC, 95teo commented on src/test/java/BogdanSandu/tests/Tema6/DemoQaWindow.java
> +            FileUtils.takeScreenshot(driver, "alertDemoQa");
Remove this line too as it's not needed. Screenshot should be taken only when getting an Exception that will cause test case to fail. Thanks!

2023-01-17 06:50 UTC, 95teo commented on src/test/java/BogdanSandu/tests/Tema7/TestDrive.java
> +package bogdanSandu.tests.Tema7;
Please remove this class from this PR. You'll add it in PR for homework 7. Thanks!

2023-01-18 06:17 UTC, 95teo commented on src/main/java/bogdanSandu/driver/BrowserManager.java
> +package BogdanSandu.driver;
Please use lowerCase when naming packages as per Java conventions. Thanks!

2023-01-18 10:32 UTC, 95teo requested changes
Please use lowerCase when naming packages as per Java conventions. Thanks!

2023-01-19 06:23 UTC, 95teo requested changes

2023-01-19 06:23 UTC, 95teo commented on src/main/java/bogdanSandu/driver/BrowserManager.java
> +package BogdanSandu.driver;
Here it seems to be package with upperCase letter. Can you please check again?

2023-01-19 06:23 UTC, 95teo commented on src/main/java/bogdanSandu/utils/FileUtils.java
> +package BogdanSandu.utils;
Here it seems to be package with upperCase letter. Can you please check again?

2023-01-19 16:27 UTC, redandreea approved these changes

2023-01-19 16:29 UTC, merged