Cosmin s/tema6
SkillBrain-com/Procyon-QAC-G1-13.10.22 pull request #26
Opened 2023-01-14 13:00 UTC by Cosmin0589

2023-01-14 13:06 UTC, sorinfoca approved these changes

2023-01-16 07:50 UTC, 95teo requested changes

2023-01-16 07:50 UTC, 95teo commented on src/main/java/cosminsechelmain/driver/BrowserManager.java
> +public class BrowserManager {
No need to create another package with this class. You already have the one from homework 5. Remove this one and use that one instead. Thanks!

2023-01-16 07:50 UTC, 95teo commented on src/main/java/cosminsechelmain/utils/FileUtils.java
> +package cosminsechelmain.utils;
Add this class in the existing cosminshechel package inside utils. No need to create cosminsechelmain package. Thanks!

2023-01-16 07:50 UTC, 95teo commented on src/test/java/cosminsechel1/tests/tema6/DemoQaWindow.java
> +package cosminsechel1.tests.tema6;
Put tema6 package inside cosminsechel.tests package. No nee to create cosminsechel1 package. Thanks!

2023-01-16 08:53 UTC, 95teo commented on src/test/java/cosminsechel/tests/tema6/DemoQaWindow.java
> +    private static File screenshot;
You can remove this line as it's never used. Thanks!

2023-01-16 08:55 UTC, 95teo commented on src/test/java/cosminsechel/tests/tema6/DemoQaWindow.java
> +            closeBrowser();
Use method from BrowserManager to close the driver. Thanks!

2023-01-16 08:55 UTC, 95teo commented on src/test/java/cosminsechel/tests/tema6/DemoQaWindow.java
> +    public static void closeBrowser() {
After you added the method from BrowserManager to close the driver delete this method from here. Thanks!

2023-01-16 08:55 UTC, 95teo commented on src/test/java/cosminsechel/tests/tema6/HerokuAlerts.java
> +    public static void closeBrowser() {
After you added the method from BrowserManager to close the driver delete this method from here. Thanks!

2023-01-16 08:56 UTC, 95teo commented on src/test/java/cosminsechel/tests/tema6/HerokuForms.java
> +    public static void closeBrowser() {
After you added the method from BrowserManager to close the driver delete this method from here. Thanks!

2023-01-16 08:56 UTC, 95teo commented on src/test/java/cosminsechel/tests/tema6/HerokuAlerts.java
> +            closeBrowser();
Use method from BrowserManager to close the driver. Thanks!

2023-01-16 08:56 UTC, 95teo commented on src/test/java/cosminsechel/tests/tema6/HerokuForms.java
> +            closeBrowser();
Use method from BrowserManager to close the driver. Thanks!

2023-01-16 08:56 UTC, 95teo commented on src/test/java/cosminsechel/tests/tema6/HerokuForms.java
> +    private static File screenshot;
You can remove this line as it's never used. Thanks!

2023-01-16 09:48 UTC, 95teo approved these changes

2023-01-16 09:48 UTC, merged