Cosminneagu/tema5
SkillBrain-com/Procyon-QAC-G1-13.10.22 pull request #28
Opened 2023-01-15 15:15 UTC by CosminN89

2023-01-16 08:00 UTC, 95teo requested changes

2023-01-16 08:00 UTC, 95teo commented on src/test/java/cosminneagu/teorie/demoqa/BrokenLinksImages.java
> +        WebElement BrokenLinksImagesSection = driver.findElement(By.xpath("/html/body/div[2]/div/div/div[2]/div[1]/div/div/div[1]/div/ul/li[7]/span"));
Use relative xpaths instead of absolute xpaths. Applicable for all classes. Thanks!

2023-01-16 08:00 UTC, 95teo commented on src/test/java/cosminneagu/teorie/demoqa/BrokenLinksImages.java
> +        BrokenLinksImagesSection.click();
camelCase when naming variables as per Java conventions. Applicable to all classes. Thanks!

2023-01-16 08:00 UTC, 95teo commented on src/test/java/cosminneagu/teorie/demoqa/Buttons.java
> +        WebElement ButtonsSection = driver.findElement(By.xpath("/html/body/div[2]/div/div/div[2]/div[1]/div/div/div[1]/div/ul/li[5]"));
camelCase and relative xpath

2023-01-16 08:00 UTC, 95teo commented on src/test/java/cosminneagu/teorie/demoqa/Buttons.java
> +        WebElement ClickMeButtons = driver.findElement(By.xpath("/html/body/div[2]/div/div/div[2]/div[2]/div[2]/div[3]/button"));
camelCase and relative xpath

2023-01-16 08:00 UTC, 95teo commented on src/test/java/cosminneagu/teorie/demoqa/CheckBox.java
> +        WebElement CheckBoxSection = driver.findElement(By.xpath("/html/body/div[2]/div/div/div[2]/div[1]/div/div/div[1]/div/ul/li[2]/span"));
camelCase and relative xpath

2023-01-16 08:00 UTC, 95teo commented on src/test/java/cosminneagu/teorie/demoqa/Links.java
> +        WebElement LinksSection = driver.findElement(By.xpath("/html/body/div[2]/div/div/div[2]/div[1]/div/div/div[1]/div/ul/li[6]"));
camelCase and relative xpath

2023-01-16 08:00 UTC, 95teo commented on src/test/java/cosminneagu/teorie/demoqa/Links.java
> +        WebElement CreatedLink = driver.findElement(By.xpath("/html/body/div[2]/div/div/div[2]/div[2]/div[2]/p[3]/a"));
camelCase and relative xpath

2023-01-16 08:00 UTC, 95teo commented on src/test/java/cosminneagu/teorie/demoqa/RadioButton.java
> +        WebElement RadioButtonSection = driver.findElement(By.cssSelector("#item-2"));
camelCase

2023-01-16 08:00 UTC, 95teo commented on src/test/java/cosminneagu/teorie/demoqa/BrokenLinksImages.java
> +package cosminneagu.teorie.demoqa;
Move package demoqa from teorie to tema5. Thanks!

2023-01-16 08:00 UTC, 95teo commented on src/test/java/cosminneagu/teorie/demoqa/TextBox.java
> +        WebElement EmailField = driver.findElement(By.id("userEmail"));
camelCase

2023-01-16 08:00 UTC, 95teo commented on src/test/java/cosminneagu/teorie/demoqa/TextBox.java
> +        WebElement TextBoxSection = driver.findElement(By.xpath("/html/body/div[2]/div/div/div[2]/div[1]/div/div/div[1]/div/ul/li[1]"));
camelCase and relative xpath

2023-01-16 08:00 UTC, 95teo commented on src/test/java/cosminneagu/teorie/demoqa/TextBox.java
> +
No need to leave one blank line after each row. Thanks!

2023-01-16 08:00 UTC, 95teo commented on src/test/java/cosminneagu/teorie/demoqa/UploadAndDownload.java
> +        WebElement UploadAndDownloadSection = driver.findElement(By.xpath("/html/body/div[2]/div/div/div[2]/div[1]/div/div/div[1]/div/ul/li[8]/span"));
camelCase and relative xpath

2023-01-16 08:00 UTC, 95teo commented on src/test/java/cosminneagu/teorie/demoqa/UploadAndDownload.java
> +
No need to leave one blank line after each line of code. Thanks!

2023-01-16 08:00 UTC, 95teo commented on src/test/java/cosminneagu/teorie/demoqa/WebTables.java
> +        WebElement AddButton = driver.findElement(By.cssSelector("#addNewRecordButton"));
camelCase

2023-01-16 08:00 UTC, 95teo commented on src/test/java/cosminneagu/teorie/demoqa/WebTables.java
> +        WebElement WebTablesSection = driver.findElement(By.cssSelector("#item-3"));
camelCase

2023-01-16 08:00 UTC, 95teo commented on src/test/java/cosminneagu/teorie/seleniumbasicspart2/ActionExample.java
> +package cosminneagu.teorie.seleniumbasicspart2;
This theory shouldn't be included in PR, so please remove it. Thanks!

2023-01-16 08:00 UTC, 95teo commented on src/test/java/cosminneagu/tests/tema5/Heroku/BasicWebPageExample.java
> +
No need to leave on blank line after each line of code. Thanks!

2023-01-16 08:00 UTC, 95teo commented on src/test/java/cosminneagu/tests/tema5/Heroku/DynamicTableTestPage.java
> +
No need to leave one blank line after each line of code. Thanks!

2023-01-16 08:00 UTC, 95teo commented on src/test/java/cosminneagu/tests/tema5/Heroku/DynamicTableTestPage.java
> +        WebElement Link4TDynamicTable = driver.findElement(By.id("dynamictablestest"));
camelCase

2023-01-16 08:00 UTC, 95teo commented on src/test/java/cosminneagu/tests/tema6/tema6.java
> +package cosminneagu.tests.tema6;
Please don't add in tema5 PR, tema6 related work. Thanks!

2023-01-22 12:21 UTC, ioanaandroflorea approved these changes

2023-01-22 17:36 UTC, zoldicatalina approved these changes

2023-01-23 06:40 UTC, 95teo requested changes

2023-01-23 06:40 UTC, 95teo commented on src/test/java/cosminneagu/tests/tema5/Heroku/ElementAttributesExamples.java
> +        WebElement AtitleFromTheSecondParagraph= driver.findElement(By.id("domattributes"));
camelCase

2023-01-23 06:40 UTC, 95teo commented on src/test/java/cosminneagu/tests/tema5/demoqa/Links.java
> +        WebElement LinksSection = driver.findElement(By.xpath("/html/body/div[2]/div/div/div[2]/div[1]/div/div/div[1]/div/ul/li[6]"));
camelCase and relative xpath

2023-01-23 06:40 UTC, 95teo commented on src/test/java/cosminneagu/tests/tema5/demoqa/Links.java
> +        WebElement LinksSection = driver.findElement(By.xpath("/html/body/div[2]/div/div/div[2]/div[1]/div/div/div[1]/div/ul/li[6]"));
Use camelCase and relative xpath

2023-01-23 06:40 UTC, 95teo commented on src/test/java/cosminneagu/tests/tema5/demoqa/Links.java
> +        WebElement CreatedLink = driver.findElement(By.xpath("/html/body/div[2]/div/div/div[2]/div[2]/div[2]/p[3]/a"));
Use camelCase and relative xpath

2023-01-23 06:40 UTC, 95teo commented on src/test/java/cosminneagu/tests/tema5/demoqa/RadioButton.java
> +        WebElement RadioButtonSection = driver.findElement(By.cssSelector("#item-2"));
Use camelCase

2023-01-23 06:40 UTC, 95teo commented on src/test/java/cosminneagu/tests/tema5/demoqa/TextBox.java
> +        WebElement TextBoxSection = driver.findElement(By.xpath("/html/body/div[2]/div/div/div[2]/div[1]/div/div/div[1]/div/ul/li[1]"));
Use camelCase and relative xpath

2023-01-23 06:40 UTC, 95teo commented on src/test/java/cosminneagu/tests/tema5/demoqa/TextBox.java
> +        WebElement EmailField = driver.findElement(By.id("userEmail"));
Use camelCase

2023-01-23 06:40 UTC, 95teo commented on src/test/java/cosminneagu/tests/tema5/demoqa/UploadAndDownload.java
> +        WebElement UploadAndDownloadSection = driver.findElement(By.xpath("/html/body/div[2]/div/div/div[2]/div[1]/div/div/div[1]/div/ul/li[8]/span"));
Use camelCase and relative xpath

2023-01-23 06:40 UTC, 95teo commented on src/test/java/cosminneagu/tests/tema5/demoqa/UploadAndDownload.java
> +        WebElement DownloadButton = driver.findElement(By.cssSelector("a[id='downloadButton']"));
Use camelCase

2023-01-23 06:40 UTC, 95teo commented on src/test/java/cosminneagu/tests/tema5/demoqa/WebTables.java
> +        WebElement WebTablesSection = driver.findElement(By.cssSelector("#item-3"));
Use camelCase

2023-01-23 06:40 UTC, 95teo commented on src/test/java/cosminneagu/tests/tema5/demoqa/WebTables.java
> +        WebElement AddButton = driver.findElement(By.cssSelector("#addNewRecordButton"));
Use camelCase

2023-01-23 06:40 UTC, 95teo commented on src/test/java/cosminneagu/tests/tema5/demoqa/WebTables.java
> +        WebElement SubmitButton = driver.findElement(By.cssSelector("button[id='submit']"));
Use camelCase

2023-01-23 06:40 UTC, 95teo commented on src/test/java/cosminneagu/tests/tema5/demoqa/WebTables.java
> +        WebElement ButtonSubmit = driver.findElement(By.cssSelector("button[type='submit']"));
Use camelCase

2023-01-23 06:40 UTC, 95teo commented on src/test/java/cosminneagu/tests/tema5/demoqa/WebTables.java
> +        WebElement TypeToSearchButton = driver.findElement(By.cssSelector("input[placeholder='Type to search']"));
Use camelCase

2023-01-24 10:34 UTC, 95teo approved these changes

2023-01-24 11:07 UTC, merged