Tema7
SkillBrain-com/Procyon-QAC-G1-13.10.22 pull request #29
Opened 2023-01-15 18:36 UTC by SanduBogdan95

2023-01-16 12:37 UTC, 95teo commented on src/test/java/bogdanSandu/tests/Tema7/CURAHealthcare.java
> +    @BeforeMethod
Can you please move @BeforeMethod and @AfterMethod to a separated abstract TestBase class and your test classes to extend that TessBase class? You have an example in the demo for chapter 7 from Timea. Thanks!

2023-01-16 12:37 UTC, 95teo commented on src/test/java/bogdanSandu/tests/Tema7/CURAHealthcare.java
> +        // go to login page
This method and invalidlogin() method can be merged into one method if you use @DataProvider. Try this approach and let me know if you have any issues. Thanks!

2023-01-18 10:41 UTC, 95teo requested changes

2023-01-18 10:41 UTC, 95teo commented on src/test/java/bogdanSandu/tests/Tema7/CURAHealthcare.java
> +public class CURAHealthcare extends TestBase {
You're not using any Assert. Consider adding on test cases.

2023-01-18 10:41 UTC, 95teo commented on src/test/java/bogdanSandu/tests/Tema7/CURAHealthcare.java
> +
You're missing bullet 3 and 5 from ex 2.

2023-01-18 10:41 UTC, 95teo commented on src/test/java/bogdanSandu/tests/Tema7/CURAHealthcare.java
> +    public void makeAppointment(String type, String username, String password){
Please double check the requirement. In order to be on appointment page you need to be logged in -> Se vor testa diferite scenarii pozitive și negative de rezervare (măcar 1 scenariu pozitiv și un scenariu negativ) Thanks!

2023-01-19 20:21 UTC, ioanaandroflorea approved these changes

2023-01-20 05:23 UTC, 95teo approved these changes

2023-01-20 05:25 UTC, merged