Bogdan sandu/tema8
SkillBrain-com/Procyon-QAC-G1-13.10.22 pull request #49
Opened 2023-01-23 20:16 UTC by SanduBogdan95

2023-01-24 13:14 UTC, 95teo requested changes

2023-01-24 13:51 UTC, SanduBogdan95 commented on src/test/java/bogdanSandu/tests/Tema8/Tests/BasicAjaxPageTest.java
> +        driver.get(StartPage);
Can you give me an example because I don't understand what you mean?

2023-01-24 16:23 UTC, 95teo commented on src/test/java/bogdanSandu/tests/Tema8/Tests/BasicAjaxPageTest.java
> +        driver.get(StartPage);
For example, you'll create in BasicAjaxPage a method `public void goToPage() {
driver.get(START_PAGE_URL);
}` and you'll call it in your test case like `basicAjaxPage.goToPage();`
The idea would be to make the interactions/actions from pages inside page object classes and not directly in test methods. You can also take a look in PR #45 or on branch teofilU/tema8 ->
![image](https://user-images.githubusercontent.com/18215854/214349291-23657284-f7cf-43f5-8b41-7f85bbbb0614.png)
If any other guidance is needed, please let me know ;)

2023-01-26 06:43 UTC, 95teo commented on src/test/java/bogdanSandu/tests/Tema8/Tests/BasicAjaxPageTest.java
> +        driver.get(StartPage);
@SanduBogdan95 ^^

2023-01-27 06:33 UTC, 95teo requested changes

2023-01-27 06:33 UTC, 95teo commented on src/test/java/bogdanSandu/tests/tema8/pageObjects/BasicAjaxPage.java
> +public class BasicAjaxPage extends BaseTest {
Please remove the extends BaseTest part. BaseTest it's the base only for test classes, not page object classes. You have a driver defined here in page class. Thanks!

2023-01-27 06:33 UTC, 95teo commented on src/test/java/bogdanSandu/tests/tema8/pageObjects/DynamicButtonsDisabledPage.java
> +public class DynamicButtonsDisabledPage extends BaseTest {
Please remove the extends BaseTest part. BaseTest it's the base only for test classes, not page object classes. You have a driver defined here in page class. Thanks!

2023-01-27 06:33 UTC, 95teo commented on src/test/java/bogdanSandu/tests/tema8/pageObjects/DynamicButtonsSimplePage.java
> +public class DynamicButtonsSimplePage extends BaseTest {
Please remove the extends BaseTest part. BaseTest it's the base only for test classes, not page object classes. You have a driver defined here in page class. Thanks!

2023-01-27 06:33 UTC, 95teo commented on src/test/java/bogdanSandu/tests/tema8/pageObjects/RedirectsPage.java
> +public class RedirectsPage extends BaseTest {
Please remove the extends BaseTest part. BaseTest it's the base only for test classes, not page object classes. You have a driver defined here in page class. Thanks!

2023-01-27 06:33 UTC, 95teo commented on src/test/java/bogdanSandu/tests/tema8/pageObjects/RefreshPage.java
> +public class RefreshPage extends BaseTest {
Please remove the extends BaseTest part. BaseTest it's the base only for test classes, not page object classes. You have a driver defined here in page class. Thanks!

2023-01-27 06:33 UTC, 95teo commented on src/test/java/bogdanSandu/tests/tema8/tests/DynamicButtonsSimplePageTest.java
> +    public void DynamicButtonsTestForDesktop(){
camelCase when naming methods as per Java conventions. Thanks!

2023-01-27 06:33 UTC, 95teo commented on src/test/java/bogdanSandu/tests/tema8/tests/DynamicButtonsSimplePageTest.java
> +    public void DynamicButtonsTestForMobile(){
camelCase when naming methods as per Java conventions. Thanks!

2023-01-27 06:33 UTC, 95teo commented on src/test/java/bogdanSandu/tests/tema8/pageObjects/BasicAjaxPage.java
> +        fluentWait((ChromeDriver) driver).until(ExpectedConditions.visibilityOfElementLocated(By.id("_valueid")));
Declare the and initialise the fluentWait either in this page constructor or in a separated WaitUtils class inside utils package.

2023-01-27 06:33 UTC, 95teo commented on src/test/java/bogdanSandu/tests/tema8/pageObjects/DynamicButtonsDisabledPage.java
> +        fluentWait((ChromeDriver) driver).until(ExpectedConditions.elementToBeClickable(By.id(BUTTON_START)));
Declare the and initialise the fluentWait either in this page constructor or in a separated WaitUtils class inside utils package.

2023-01-27 06:33 UTC, 95teo commented on src/test/java/bogdanSandu/tests/tema8/pageObjects/DynamicButtonsSimplePage.java
> +        fluentWait((ChromeDriver) driver).until(ExpectedConditions.elementToBeClickable(By.id(START_BUTTON)));
Declare the and initialise the fluentWait either in this page constructor or in a separated WaitUtils class inside utils package.

2023-01-27 06:33 UTC, 95teo commented on src/test/java/bogdanSandu/tests/tema8/pageObjects/RedirectsPage.java
> +        fluentWait((ChromeDriver) driver).until(ExpectedConditions.visibilityOfElementLocated(By.id(BACK_BUTTON)));
Declare the and initialise the fluentWait either in this page constructor or in a separated WaitUtils class inside utils package.

2023-01-27 12:07 UTC, sorinfoca approved these changes

2023-01-27 12:13 UTC, ioanaandroflorea approved these changes

2023-01-28 17:10 UTC, 95teo approved these changes

2023-01-28 17:11 UTC, merged