Cosmin s/tema8
SkillBrain-com/Procyon-QAC-G1-13.10.22 pull request #53
Opened 2023-01-24 21:49 UTC by Cosmin0589

2023-01-25 06:26 UTC, 95teo requested changes

2023-01-25 06:26 UTC, 95teo commented on src/test/java/cosminsechel/tests/tema8/TestPage/BaseTest.java
> +package cosminsechel.tests.tema8.TestPage;
Please rename the name of the package from TestPage -> testpage (lowercase for package names as per Java conventions). Thanks!

2023-01-25 06:26 UTC, 95teo commented on src/test/java/cosminsechel/tests/tema8/TestPage/BaseTest.java
> +
Add implementation for BaseTest. Here you should have before and after methods for setting up drivers for mobile/desktop, closing browsers.

2023-01-25 06:26 UTC, 95teo commented on src/test/java/cosminsechel/tests/tema8/TestPage/TestPages.java
> +
Add implementation for tests using Page Objects created in pages package.

2023-01-25 13:38 UTC, tincageorgianaalina approved these changes

2023-01-25 17:52 UTC, 95teo requested changes
You're still missing the .xml files in resources for mobile and desktop groups/suites of tests in order to run tests for mobile/desktop separately.

2023-01-25 17:52 UTC, 95teo commented on src/test/java/cosminsechel/tests/tema8/testpage/TestPages.java
> +        driver.navigate().back();
No need to navigate back. You can remove this line or add an assert to check after it to check that the url has changed. Thanks!

2023-01-25 17:52 UTC, 95teo commented on src/test/java/ioananadroflorea/tests/Tema7/BaseTest.java
> -import ioanaandroflorea.driver.BrowserManager;
Change ioanaandroflorea to ioanandroflorea and remove the import for your package. Thanks!

2023-01-25 17:52 UTC, 95teo commented on src/test/java/ioananadroflorea/tests/Tema7/BaseTest.java
> +        driver = BrowserManager.createDriver();
Revert this change. Thanks!

2023-01-26 06:52 UTC, 95teo approved these changes

2023-01-26 07:40 UTC, merged