Alina tinca/tema8
SkillBrain-com/Procyon-QAC-G1-13.10.22 pull request #54
Opened 2023-01-25 13:08 UTC by tincageorgianaalina

Am adaugat tema 8

2023-01-25 18:06 UTC, curtnazarEliz approved these changes

2023-01-25 19:26 UTC, ioanaandroflorea approved these changes

2023-01-26 07:18 UTC, 95teo requested changes
Please solve also your conflicts. Thanks!

2023-01-26 07:18 UTC, 95teo commented on src/test/resources/alinaTinca/suiteTema8Desktop.xml
> +<suite name="Homework8-Desktop Test Suite" verbose="1" >
Why are suite.xml and group.xml files empty? Please refer to #39 and put the content back inside them. Thanks!

2023-01-26 07:18 UTC, 95teo commented on src/test/java/alinaTinca/tests/Tema8/tests/JavaScriptRedirectsPageTests.java
> +//        Assert.assertEquals(driver.getCurrentUrl(),
In order to assert urls, you'll usually have to wait for page to load.

2023-01-26 07:18 UTC, 95teo commented on src/test/java/alinaTinca/tests/Tema8/pageObjects/SimpleDynamicButtonConfirmationPage.java
> +    public String displayTextAfterClickAllButtons(){
This method duplicates displayTextBeforeClickAllButtons() method. You can delete one of them and keep only one an use it in your test whenever needed.

2023-01-26 07:18 UTC, 95teo commented on src/test/java/alinaTinca/tests/Tema8/pageObjects/RefreshPage.java
> +    public String getRefreshedTimestamp(){
This method duplicates getCurrentTimestamp() method. You can delete one of them and keep only one an use it in your test whenever needed.

2023-01-26 07:18 UTC, 95teo commented on src/test/java/alinaTinca/tests/Tema8/pageObjects/DisabledDynamicButtonConfirmationPage.java
> +    public String displayTextAfterClickAllButtons(){
This method duplicates displayTextBeforeClickAllButtons() method. You can delete one of them and keep only one an use it in your test whenever needed.

2023-01-28 16:56 UTC, 95teo requested changes

2023-01-28 16:56 UTC, 95teo commented on src/test/resources/alinatinca/suite.xml
> -<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
Please don't delete this suite.xml as it was used for Tema 7. Add it in the same directory with the one for desktop and mobile. Thanks!

2023-01-28 16:56 UTC, 95teo commented on src/test/java/alinaTinca/tests/Tema8/pageObjects/DisabledDynamicButtonConfirmationPage.java
> +    public String displayTextAfterClickAllButtons(){
You still have two methods here. Choose only one to use in your tests and delete the other one. Thanks!

2023-01-28 18:42 UTC, 95teo approved these changes

2023-01-29 09:35 UTC, merged