Neculaclaudiu/tema8
SkillBrain-com/Procyon-QAC-G1-13.10.22 pull request #58
Opened 2023-01-27 16:12 UTC by Claudiu357

2023-01-28 17:18 UTC, 95teo requested changes

2023-01-28 17:18 UTC, 95teo commented on src/test/java/ioananadroflorea/tests/Tema7/BaseTest.java
> +import ioanaandroflorea.driver.BrowserManager;
Please don't modify this file. Revert this change. Thanks!

2023-01-28 17:18 UTC, 95teo commented on src/test/java/neculaclaudiu/tests/seleniumpart3/tests/AllTests.java
> +    public void JavaScriptRedirectsPageTest(){
camelCase when naming methods as per Java conventions. Thanks!

2023-01-28 17:18 UTC, 95teo commented on src/test/java/neculaclaudiu/tests/seleniumpart3/tests/AllTests.java
> +    public void SimpleDynamicButtonsPageTest(){
camelCase when naming methods as per Java conventions. Thanks!

2023-01-28 17:18 UTC, 95teo commented on src/test/java/neculaclaudiu/tests/seleniumpart3/tests/AllTests.java
> +    public void DisabledDynamicButtonsTest(){
camelCase when naming methods as per Java conventions. Thanks!

2023-01-29 08:15 UTC, 95teo approved these changes
Please don't forget to ask for a colleague review too before being able to do the merge. Thanks!

2023-01-30 12:05 UTC, sorinfoca approved these changes

2023-01-30 12:33 UTC, merged