Cosmin s/tema9
SkillBrain-com/Procyon-QAC-G1-13.10.22 pull request #59
Opened 2023-01-28 13:10 UTC by Cosmin0589

2023-01-28 13:11 UTC, sorinfoca approved these changes

2023-01-28 17:33 UTC, 95teo requested changes

2023-01-28 17:33 UTC, 95teo commented on src/main/java/cosminsechel/driver/BrowserManager.java
> +    }
Please add driver.quit(); line in this method too. Thanks!

2023-01-29 08:09 UTC, 95teo requested changes
Drag & drop tema8 package from ioanandroflorea package to your package -> cosminsechel -> tests Thanks!

2023-01-29 16:02 UTC, 95teo approved these changes

2023-01-29 21:46 UTC, merged