Tema9
SkillBrain-com/Procyon-QAC-G1-13.10.22 pull request #62
Opened 2023-01-29 12:39 UTC by SanduBogdan95

2023-01-29 15:17 UTC, ioanaandroflorea approved these changes

2023-01-29 16:39 UTC, 95teo requested changes

2023-01-29 16:39 UTC, 95teo commented on src/main/java/bogdanSandu/driver/BrowserManager.java
> +            return new RemoteWebDriver(new URL("http://localhost:4444/ui"), new ChromeOptions());
Please change the url from "http://localhost:4444/ui" to "http://localhost:4444/". Thanks!

2023-01-29 16:39 UTC, 95teo commented on src/main/java/bogdanSandu/driver/BrowserManager.java
> +    public static RemoteWebDriver creatRemoteWebDriver(){
Please also rename method from creatRemoteWebDriver() to createRemoteWebDriver(). Thanks!

2023-01-30 07:28 UTC, 95teo approved these changes

2023-01-30 07:29 UTC, merged