Neculaclaudiu/tema9
SkillBrain-com/Procyon-QAC-G1-13.10.22 pull request #66
Opened 2023-01-30 20:20 UTC by Claudiu357

2023-01-31 06:28 UTC, 95teo requested changes

2023-01-31 06:28 UTC, 95teo commented on src/test/java/sorinfoca/Tests/teofilursan/tests/seleniumpart1/SeleniumExampleTest.java
> +package sorinfoca.Tests.teofilursan.tests.seleniumpart1;
Please move back this package. Thanks!

2023-01-31 10:54 UTC, 95teo requested changes
You only changed it in the file. Please drag and drop the whole package back to it´s place in test -> java package. Thanks!
![image](https://user-images.githubusercontent.com/18215854/215741144-f77d35d9-43f4-4d3a-a52f-c83004c3b407.png)

2023-01-31 12:13 UTC, 95teo requested changes

2023-01-31 12:13 UTC, 95teo commented on src/test/java/sorinfoca/Tests/Tema6/DemoQaWindow.java
> +package andreeaG.sorinfoca.Tests.Tema6;
It seems like you moved sorinfoca package inside andreeaG package. If you can revert this change too. If not, we'll take it in today's meeting. Thanks!

2023-02-01 07:23 UTC, 95teo approved these changes

2023-02-01 07:55 UTC, SanduBogdan95 approved these changes

2023-02-01 11:38 UTC, merged