elizCurtnazar/tema9
SkillBrain-com/Procyon-QAC-G1-13.10.22 pull request #69
Opened 2023-02-02 10:01 UTC by curtnazarEliz

2023-02-02 11:00 UTC, 95teo requested changes
Please remove Logs folder and also add tema8 with grid also. Thanks!

2023-02-02 11:00 UTC, 95teo commented on src/test/java/elizCurtnazar/tests/tema9/gridtema5/BothPagesTests.java
> +        BrowserManager.closeRemoteWebdriver(remoteWebDriver);
Please also create this method in BrowserManager class as it's not defined there yet. Thanks!

2023-02-03 06:48 UTC, 95teo approved these changes

2023-02-03 13:41 UTC, zoldicatalina approved these changes

2023-02-03 14:25 UTC, merged