Pentru corectat tema6
SkillBrain-com/Procyon-QAC-G1-13.10.22 pull request #73
Opened 2023-02-04 17:35 UTC by zoldicatalina

2023-02-04 20:51 UTC, ioanaandroflorea approved these changes

2023-02-05 08:23 UTC, 95teo requested changes
Please delete Logs folder as we don't want to check in the screenshots. Thanks!

2023-02-06 09:36 UTC, 95teo requested changes

2023-02-06 09:36 UTC, 95teo commented on src/test/java/catalinazoldi/tests/Tema7/CuraHealthcare.java
> +package catalinazoldi.tests.Tema7;
Please don't add this yet. They'll be added on tema 7. Thanks!

2023-02-06 09:36 UTC, 95teo commented on src/test/java/catalinazoldi/tests/Tema7/TestBase.java
> +package catalinazoldi.tests.Tema7;
Please don't add this yet. They'll be added on tema 7. Thanks!

2023-02-06 11:32 UTC, 95teo approved these changes

2023-02-07 07:15 UTC, merged