Catalinaz/tema7
SkillBrain-com/Procyon-QAC-G1-13.10.22 pull request #75
Opened 2023-02-10 15:26 UTC by zoldicatalina

2023-02-10 20:02 UTC, ioanaandroflorea approved these changes

2023-02-13 07:13 UTC, 95teo requested changes

2023-02-13 07:13 UTC, 95teo commented on src/test/java/catalinazoldi/tests/Tema7/CURAHealthcare.java
> +
One blank line it's enough here. Please remove the extra ones. Thanks!

2023-02-13 07:13 UTC, 95teo commented on src/test/java/teofilursan/tests/seleniumpart1/SeleniumExampleTest.java
> +import ioanandroflorea.driver.BrowserManager;
Please leave `import teofilursan.driver.BrowserManager;` and not add ioana's one as it's my package. Thanks!

2023-02-13 07:13 UTC, 95teo commented on src/test/resources/tema7catalinaz/suite.xml
> +<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
Use CURAHealthcare from tests/Tema7 package and not the one from teorie/TestNg package. Thanks!

2023-02-13 07:13 UTC, 95teo commented on src/test/resources/tema7catalinaz/suite.xml
> +            <class name="catalinazoldi.teorie.TestNg.CuraHealthcareTests"/>
Use CURAHealthcare from tests/Tema7 package and not the one from teorie/TestNg package. Thanks!

2023-02-13 07:13 UTC, 95teo commented on src/test/resources/zoldicatalina/groups-tests.xml
> +<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
You either try to use your groups/classes from teorie/TestNg package with proper changes or you remove this file. Thanks!

2023-02-13 07:13 UTC, 95teo commented on src/test/resources/zoldicatalina/suite.testing.xml
> +<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
You either try to use your groups/classes from teorie/TestNg package or you remove this file. Thanks!

2023-02-15 18:28 UTC, zoldicatalina commented on src/main/java/test/sample/ParameterSample.java
> +package test.sample;
Theo , nu gasesc clasa asta pentru a putea sa o sterg.

2023-02-15 18:28 UTC, zoldicatalina commented on src/main/java/test/sample/ParameterTest.java
> +
Nici pe asta.

2023-02-16 07:06 UTC, 95teo requested changes

2023-02-16 07:06 UTC, 95teo commented on src/test/resources/tema7catalinaz/groups.xml
> +<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
Please rename folder `tema7catalinaz ` to `catalinazoldi`. Thanks!
![image](https://user-images.githubusercontent.com/18215854/219291814-4d21caed-5532-4bee-984e-0cf8969fa2aa.png)

2023-02-16 07:06 UTC, 95teo commented on src/test/java/catalinazoldi/tests/Tema7/CURAHealthcare.java
> +        facility.selectByVisibleText("Tokyo CURAHealthcare Center");
Be careful about the option you choose. You're missing a space -> `Tokyo CURA Healthcare Center`

2023-02-16 07:06 UTC, 95teo commented on src/test/java/catalinazoldi/tests/Tema7/CURAHealthcare.java
> +            driver.getCurrentUrl();
Don't forget to add the assertion. Thanks!

2023-02-16 07:06 UTC, 95teo commented on src/test/java/catalinazoldi/tests/Tema7/CURAHealthcare.java
> +                    By.cssSelector("#login > div > div > div.col-sm-12.text-center > p.lead.text-danger")));
Don't forget to add the assertion. Thanks!

2023-02-17 06:17 UTC, 95teo requested changes

2023-02-17 06:17 UTC, 95teo commented on src/test/java/catalinazoldi/tests/Tema7/CURAHealthcare.java
> +                    By.cssSelector("#login > div > div > div.col-sm-12.text-center > p.lead.text-danger")));
You're missing the brackets for else branch. It should be like this for else ->
` else {`
 `    wait.until(ExpectedConditions.presenceOfElementLocated(`
 `                   By.cssSelector("#login > div > div > div.col-sm-12.text-center > p.lead.text-danger")));`
 `    assertEquals("https://katalon-demo-cura.herokuapp.com/profile.php#login", driver.getCurrentUrl());`
`}`

2023-02-18 19:35 UTC, 95teo approved these changes

2023-02-19 07:43 UTC, merged