Catalinazoldi/capitolul8
SkillBrain-com/Procyon-QAC-G1-13.10.22 pull request #79
Opened 2023-02-25 19:05 UTC by zoldicatalina

2023-02-25 23:05 UTC, ioanaandroflorea approved these changes

2023-02-26 07:20 UTC, SanduBogdan95 approved these changes

2023-03-01 12:39 UTC, 95teo requested changes

2023-03-01 12:39 UTC, 95teo commented on src/main/java/catalinazoldiSeleniumBasics2/driver/BrowserManager.java
> +package catalinazoldiSeleniumBasics2.driver;
Please create a `teorie `package in `src/main/java/catalinazoldi` package and move this BrowserManager class there. After you move the class, please remove `catalinazoldiSeleniumBasics2` package from `src/main/java`. Thanks!

2023-03-01 12:39 UTC, 95teo commented on src/test/java/catalinazoldiSeleniumBasics2/teorie/SBpart3/pageObject/EmagHomePage.java
> +package catalinazoldiSeleniumBasics2.teorie.SBpart3.pageObject;
Please move `SBpart3`package in `src/test/java/catalinazoldi/teorie` package. After you move the `SBpart3`, please remove catalinazoldiSeleniumBasics2 package from `src/test/java`. Thanks!
![image](https://user-images.githubusercontent.com/18215854/222141441-38fe37fa-97bb-4181-a7e0-1a9a958e9939.png)

2023-03-03 06:08 UTC, 95teo requested changes
Please also add .xml files to run suites for mobile and desktop. You have many examples in `resources` folder on other colleagues folders ->
![image](https://user-images.githubusercontent.com/18215854/222644471-2c25e946-4f7e-4741-8e4a-6a016cb9ad1e.png)

2023-03-03 14:49 UTC, 95teo requested changes

2023-03-03 14:49 UTC, 95teo commented on src/test/resources/catalinazoldi/Mobile.xml
> +                <exclude name="Desktop"/>
"desktop" instead of "Desktop". That's how you named the groups in test classes.

2023-03-03 14:49 UTC, 95teo commented on src/test/resources/catalinazoldi/Desktop.xml
> +                <exclude name="Mobile"/>
"mobile" instead of "Mobile". That's how you named the groups in test classes.

2023-03-03 14:49 UTC, 95teo commented on src/test/resources/catalinazoldi/Desktop.xml
> +    </test>
Please add at the end missing `</suite>` closing tag. Thanks!

2023-03-03 14:49 UTC, 95teo commented on src/test/java/catalinazoldi/tests/Tema8/tests/BasicAjaxTest.java
> +    @Test(groups = "Desktop")
"desktop" instead of "Desktop"

2023-03-03 14:49 UTC, 95teo commented on src/test/java/catalinazoldi/tests/Tema8/tests/BasicAjaxTest.java
> +    @Test(groups = "Mobile")
"mobile" instead of "Mobile"

2023-03-03 15:38 UTC, 95teo approved these changes

2023-03-03 19:23 UTC, merged